import type { INestApplication } from '@nestjs/common';
import { DocumentBuilder, type OpenAPIObject, SwaggerModule } from '@nestjs/swagger';

import { APP_VERSION } from './config/version.js';

/** Single source for the OpenAPI document: served at /docs and written to docs/ by `pnpm docs:api`. */
export function buildOpenApiDocument(app: INestApplication): OpenAPIObject {
  const config = new DocumentBuilder()
    .setTitle('CommercePilot API')
    .setDescription(
      'E-commerce backend with a conversational assistant. Every response uses the envelope ' +
        '`{ success, data, meta }` or `{ success: false, error: { code, message, details?, requestId } }`.',
    )
    .setVersion(APP_VERSION)
    .addBearerAuth()
    .addApiKey({ type: 'apiKey', in: 'header', name: 'x-admin-key' }, 'admin-key')
    .build();
  return SwaggerModule.createDocument(app, config);
}

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

/** Renders a deterministic Markdown endpoint reference from the OpenAPI document. */
export function renderApiMarkdown(doc: OpenAPIObject): string {
  const rows: string[] = [];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const method of METHODS) {
      const op = item[method];
      if (!op) continue;
      const security = (op.security ?? []).flatMap((s) => Object.keys(s));
      const auth = security.includes('admin-key')
        ? 'admin key'
        : security.includes('bearer')
          ? 'bearer'
          : '—';
      const success = Object.keys(op.responses ?? {})
        .filter((code) => code.startsWith('2'))
        .join(', ');
      const params = (op.parameters ?? [])
        .map((p) => ('name' in p ? `\`${p.name}\`` : ''))
        .filter(Boolean)
        .join(', ');
      const ref = (op.requestBody as { content?: Record<string, { schema?: { $ref?: string } }> })
        ?.content?.['application/json']?.schema?.$ref;
      const body = ref ? `\`${ref.split('/').pop()}\`` : '—';
      const summary = (op.summary ?? op.description ?? '').replace(/\|/g, '\\|');
      rows.push(
        `| ${method.toUpperCase()} | \`${path}\` | ${auth} | ${params || '—'} | ${body} | ${success} | ${summary} |`,
      );
    }
  }

  return [
    '<!-- GENERATED by `pnpm docs:api` from the OpenAPI document. Do not edit by hand. -->',
    '',
    `# API reference (v${doc.info.version})`,
    '',
    'Interactive docs: `/docs` (Swagger UI). Machine-readable spec: [`openapi.json`](openapi.json).',
    '',
    doc.info.description ?? '',
    '',
    '| Method | Path | Auth | Parameters | Body | Success | Summary |',
    '| ------ | ---- | ---- | ---------- | ---- | ------- | ------- |',
    ...rows,
    '',
  ].join('\n');
}
